@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImlhdCI6MTcwMjAzODMzOSwiZXhwIjoxNzAyMDgxNTM5fQ.FrP1au4lD-dnBCyxoDk7IQtq6bJD-pDDuQ47qHf9oys
GET http://localhost:3000/products?sort=asc
###
GET http://localhost:3000/products/7

### 
POST http://localhost:3000/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "알파",
    "description": "첫번째"
}
###
PUT http://localhost:3000/products/30
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "알파",
    "description": "첫번째"
}
###
DELETE http://localhost:3000/products/30
Content-Type: application/json
Authorization: Bearer {{token}}

